name: text_zipper
description: A two dimensional text zipper data structure.
version: 0.1.0
author: Kwang Yul Seo <kwangyul.seo@gmail.com>
homepage: https://github.com/kseo/text_zipper

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  quiver_check: '>=1.0.0-dev.1<1.1.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
